# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.ljds_extension:
        class: LjdsBundle\Twig\LjdsExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: [@doctrine.orm.entity_manager]
    app.twitter:
        class: LjdsBundle\Service\TwitterService
        arguments: [@service_container, @router]
    app.facebook:
        class: LjdsBundle\Service\FacebookService
        arguments: [@service_container, @router]
    app.recaptcha:
        class: LjdsBundle\Service\ReCAPTCHAService
        arguments: [@service_container]
    app.gif:
        class: LjdsBundle\Service\GifService
        arguments:
            em: "@doctrine.orm.entity_manager"
            facebookAutopost: "%facebook_autopost%"
            facebookService: "@app.facebook"
            twitterAutopost: "%twitter_autopost%"
            twitterService: "@app.twitter"
