services:
    # Twig extension
    app.ljds_extension:
        class: LjdsBundle\Twig\LjdsExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"


    # Services
    app.twitter:
        class: LjdsBundle\Service\TwitterService
        arguments:
            container: "@service_container"
            router: "@router"

    app.facebook:
        class: LjdsBundle\Service\FacebookService
        arguments:
            container: "@service_container"
            router: "@router"

    app.facebook_likes:
        class: LjdsBundle\Service\FacebookLikesService
        arguments:
            domains: "%domains%"
            router: "@router"
            em: "@doctrine.orm.entity_manager"
            memcached: "@memcached_cache"
            facebookAppId: "%facebook_app_id%"
            facebookAppSecret: "%facebook_app_secret%"
            facebookAccessToken: "%facebook_access_token%"

    app.recaptcha:
        class: LjdsBundle\Service\ReCAPTCHAService
        arguments:
            container: "@service_container"

    app.gif:
        class: LjdsBundle\Service\GifService
        arguments:
            em: "@doctrine.orm.entity_manager"
            mailService: "@app.mail_service"
            facebookAutopost: "%facebook_autopost%"
            facebookService: "@app.facebook"
            twitterAutopost: "%twitter_autopost%"
            twitterService: "@app.twitter"
            pushEnabled: "%push_enabled%"
            pushService: "@app.push_notifications"

    app.sitemap.listener:
        class: LjdsBundle\EventListener\SitemapListener
        arguments:
            router: "@router"
            em: "@doctrine.orm.entity_manager"
        tags: [{name: "presta.sitemap.listener"}]

    app.gif_downloader:
        class: LjdsBundle\Service\GifDownloaderService
        arguments:
            kernelRootDir: "%kernel.root_dir%"
            requestContextHost: "%router.request_context.host%"
            requestContextScheme: "%router.request_context.scheme%"
            requestContextBaseUrl: "%router.request_context.base_url%"
            em: "@doctrine.orm.entity_manager"

    app.mail_service:
        class: LjdsBundle\Service\MailService
        arguments:
            mailer: "@mailer"
            twig: "@twig"
            router: "@router"
            sender_email: "%mailer_sender_email%"

    app.push_notifications:
        class: LjdsBundle\Service\PushNotificationsService
        arguments:
            em: "@doctrine.orm.entity_manager"
            buzz: "@buzz"
            router: "@router"
            apiKey: "%push_public_api_key%"
